import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const guideSidebars: SidebarsConfig = {
  guideSidebar: [{type: 'autogenerated', dirName: '.'}],
};

export default guideSidebars;